.github/workflows/codespell.yml, .goreleaser.yaml, README.md, gui/cloudfuse_gui.spec, gui/create_gui.sh
This changes go releaser to include the GUI in the zip and tar files for Windows and Linux.
- Closes #
=> Include gui when doing go releaser

component/s3storage/client_test.go, component/s3storage/s3wrappers.go
List() is supposed to exclude the directory being listed. But when listing the root, "/" comes up as a subdirectory.
By simply truncating the directory name before adding it, we can detect that this is the directory being listed, and should not be included.
- Closes #
=> Bugfix: Two "." entries when listing root of S3 mount

CHANGELOG.md, azure-pipeline-templates/e2e-tests-spcl.yml, azure-pipeline-templates/e2e-tests.yml, azure-pipeline-templates/verbose-tests.yml, cmd/health-monitor.go, cmd/health-monitor_test.go, component/azstorage/block_blob.go, component/azstorage/config.go, component/azstorage/connection.go, component/azstorage/datalake.go, component/file_cache/file_cache.go, component/file_cache/file_cache_linux_test.go, component/file_cache/file_cache_test.go, gui/common_qt_functions.py, setup/baseConfig.yaml, test/e2e_tests/dir_test.go, test/e2e_tests/file_test.go, test/scripts/fsync_sample.c, testdata/config/azure_key_symlink.yaml
[Upstream changed sync-to-flush to flush immediately on sync calls.](https://github.com/Azure/azure-storage-fuse/pull/1281)
This PR merges that in, and sets sync-to-flush true by default.
Note: This PR will be merged without squashing, in order to provide a good merge-base for future upstream merges.
- Related PR #31, 
- Related Issue https://github.com/Azure/azure-storage-fuse/issues/1259
=> Merge upstream sync-to-flush fix and set it true by default

component/libfuse/libfuse2_handler.go
We were giving file ownership to the "current user" (-1), but when launching as a service, the current user is SYSTEM, which does not allow files to be modified by any users (including admin!).
This changes ownership to the "Authenticated Users" group, which allows writes but stops short of allowing writes for the EVERYONE group.
This bug, and the unsophisticated fix this PR introduces suggest that we need to give more serious treatment to security / permissions on Windows at some future point.
- Closes #
=> Bugfix: Access Denied on Windows When Running as a Service

cmd/doc_test.go, cmd/health-monitor_test.go, cmd/mount_linux_test.go, cmd/mount_windows_test.go, cmd/root_test.go, cmd/secure_test.go, cmd/service_windows_test.go, cmd/unmount_linux_test.go, component/attr_cache/attr_cache_test.go, component/azstorage/config_test.go, component/block_cache/block_cache_linux_test.go, component/file_cache/cache_policy_test.go, component/file_cache/file_cache_linux_test.go, component/file_cache/file_cache_test.go, component/file_cache/file_cache_windows_test.go, component/file_cache/lfu_policy_test.go, component/file_cache/lru_policy_test.go, component/libfuse/libfuse2_handler_test_wrapper.go, component/s3storage/config_test.go, component/stream/read_test.go, tools/health-monitor/monitor/cpu_mem_profiler/cpu_mem_monitor_test.go
Whenever we call panic with a literal string, this PR adds the underlying error to the string.
- Closes #
=> Print underlying error when panicking

README.md, build/windows_installer_build.iss, gui/common_qt_functions.py
Windows installer now create a Cloudfuse directory in the users AppData folder.
- Closes #
=> Create app data folder on install

gui/mountPrimaryWindow.py
Mount function now checks if mount directory was created successfully before reporting status back to the user. This should prevent mount from failing silently.
Add functions to handle subprocess consistently.
Status messages are appended to the contents of the status text field instead of replacing them.
- Closes #
=> Improve Windows GUI Mount Error Handling

.goreleaser.yaml, build/windows_installer_build.iss, sampleFileCacheConfigAzure.yaml, sampleFileCacheConfigS3.yaml, sampleFileCacheWithSASConfigAzure.yaml, setup/baseConfig.yaml
Set option true in sample configs and deploy file cache with S3 as default config on Windows (without overwriting any existing config).
GoReleaser doesn't have an option to prevent overwriting, so no default config is deployed on Windows.
- Closes #
=> Sample config allow non empty temp

gui/common_qt_functions.py
If the GUI fails to write the config file, a warning window will pop up, and the config window will not longer close on its own. 
Fixed a bug where the code fails when the config or default_config files are empty, use the built in programmed default values if all else fails.
- Closes #
=> Keep window open on failed write in GUI

component/file_cache/file_cache.go, setup/baseConfig.yaml
We shouldn't clear the file cache on unmount, if we're trying to persist it with allow-non-empty-temp.
- Closes #
=> Keep file cache on shutdown.

gui/common_qt_functions.py
The GUI will now find the center of the primary screen to open the widget windows. Prior to this change, the code would open the window on top of the primary window, but sometimes it would get lost and open in outside the scope of the desktop.
- Closes #
=> set initial window positions to center of desktop

component/attr_cache/attr_cache.go, component/attr_cache/attr_cache_test.go
Just a quick correction for attr_cache
- Closes #
=> Always use createObjAttr (not &objAttr{})

.github/workflows/publish-release.yml, .goreleaser.yaml
This fixes a naming issue in our released files where some file had an extra "." before the release version and other inconsistencies such as some referring to x86_64 and amd64. This has been fixed by using the default name in goreleaser for the releases.
Additionally, I fixed the name for the windows executable so it should follow the same filename as the rest of the files that goreleaser uses.
- Closes #
=> Fix release file name issue

component/attr_cache/attr_cache.go
This prevents race conditions taking place in the attribute cache by using write locks instead of the read locks that were in place in the functions where attribute cache items are being modified. 
- Closes #
=> Prevent races in attr cache

common/types.go, component/libfuse/statfs_windows.go
The size of the mounted directory on Windows is now reported as empty with a size of 1 PB. Before it was reporting an identical size of the users C: drive. This should signify that it is a cloud mount and is similar to an approach that rclone uses.
- Closes #
=> Fix size of windows directory

gui/common_qt_functions.py, gui/mountPrimaryWindow.py, setup/baseConfig.yaml
Remove s3storage profile "default" from GUI default config (having it set to 'default' prevents config credentials from being used).
Remove erronious documentation which said profile defaults to "default" (it actually defaults to an empty string).
- Closes #
=> Fix broken 1.0

component/attr_cache/attr_cache.go, component/attr_cache/attr_cache_test.go, component/attr_cache/cacheMap.go, component/libfuse/libfuse2_handler.go, component/s3storage/s3storage.go, component/s3storage/s3wrappers.go, internal/mock_component.go, setup/baseConfig.yaml
Bugfix: bad math in S3storage::StreamDir.
Keep filling dir list cache when OS re-lists from the beginning (>MaxDirListCount entries).
Use attr_cache to respond to StreamDir and ReadDir without using cloud storage.
Respect attr_cache `timeout-sec`.
Use repeated OS `Readdir` calls with zero offset to complete directory listing despite bad OS behavior.
- Closes [#81](https://github.com/Seagate/cloudfuse/issues/81)
=> Cache Directory List

.gitignore, cmd/mount.go, component/attr_cache/attr_cache.go, component/attr_cache/attr_cache_test.go, component/attr_cache/cacheMap.go, component/attr_cache/cacheMap_test.go, component/azstorage/azstorage.go, component/file_cache/file_cache.go, component/libfuse/libfuse.go, component/libfuse/libfuse2_handler.go, component/s3storage/s3storage.go, component/s3storage/s3storage_test.go, component/s3storage/s3wrappers.go, test/e2e_tests/data_validation_test.go, test/e2e_tests/dir_test.go, test/e2e_tests/file_test.go, test/mount_test/mount_test.go, test/stress_test/stress_test.go
Change libfuse::Readdir to use fill properly with a non-zero offset
Add directory listing cache to attr_cache to serve concurrent StreamDir requests
This improves performance for Readdir by another 2x. I now see cached Readdir calls serving >8k entries in <30ms.
There is a fair amount of refactoring in this one:
- The attribute cacheMap insert function now takes an options struct
- Attribute cache items now have a handle to their parents
- Directories now have a map of listing cache segments, and each segment now has its own timestamp (and they each expire independently)
- A directory's listing cache is cleared when its contents change (except when the cache is being filled by listing from cloud storage)
- Libfuse::Readdir is broken up into a few functions for improved readability
- The …
=> Concurrency and Coherency for Directory Listing Cache

cmd/unmount_all.go, doc/cloudfuse_mount.md, doc/cloudfuse_mount_all.md, doc/cloudfuse_mount_list.md
This updates some of the docs with some of the flags that were changed in blobfuse2.2.0, namely the flags surrounding the block cache. Additionally, it fixes a comment that no longer applies with the unmount all command on Linux.
- Closes #
=> Cleanup docs

.github/workflows/trivy.yaml
Now that we have access to GitHub security tab, trivy can now upload its security results to our GitHub security tab.
- Closes #
=> Trivy can now upload results to GitHub security tab

cmd/secure.go, cmd/secure_test.go
Using `secure encrypt` and `secure decrypt` without the --output-file parameter currently writes the file to a default .cloudfuse directory. Now, instead it use the same filename as the original file. Encrypt will now add the ".aes" extension for an aes encrypted to the file name. And decrypt will remove the ".aes" extension by default. This has the added benefit that running encrypt and decrypt right after each other will produce the original file with the same file name.
Additionally, secure decrypt did not delete the encrypted file. I have changed that so decrypt now deletes the file.
- Closes #
=> Change secure to use config file name when encrypting files

.github/workflows/unit-test.yml
This skips the dependabot ci/cd pipeline for Windows. These will all fail with dependabot since this ci/cd pipeline needs access to specific github secrets. So since the test will always fail, we should skip it.
- Closes #
=> Skip ci/cd on windows for dependabot updates

gui/common_qt_functions.py, gui/mountPrimaryWindow.py, gui/s3_config_common.ui
- Use system path to find cloudfuse CLI, and only use current directory as a fallback.
- Set allow-other to false by default, since Linux fuse throws an error
- Use the same mount logic for Windows and Linux
- Closes #
=> GUI: Look for cloudfuse CLI in path

component/file_cache/cache_policy_test.go, component/file_cache/file_cache.go, component/file_cache/file_cache_linux_test.go, component/file_cache/file_cache_test.go, component/file_cache/file_cache_windows_test.go, component/file_cache/lfu_policy_test.go, component/file_cache/lru_policy_test.go
Change file cache `invalidateDirectory` to delete files in order (children first)
Also added error logging for `os.RemoveAll`
- Closes #
=> Bugfix: File cache rename directory fails to remove source directory

component/attr_cache/attr_cache.go, component/file_cache/file_cache.go, component/libfuse/libfuse2_handler.go
Disable certain logs for GetAttr calls which noticeably affect performance.
- Closes #
=> Don't log getattr calls in libfuse, attr_cache, or file_cache

go.mod
This fixes our go.mod file to use the newer 1.N.P syntax https://go.dev/doc/toolchain#version to specify the version of Go being used. This now will use a 1.22.0 toolchain to build Go. This also fixes a warning from CodeQL and an issue with Mend.
- Closes #
=> Use new syntax for go version in go.mod file

.github/workflows/publish-release.yml, .goreleaser.yaml
Changes our C compiler to use Zig https://ziglang.org/, which allows easier cross compilation support. This should allow us to deploy Cloudfuse to more Linux OS's without needing to change our deployment strategy or spin up VM's and docker images.
- Closes #
=> Use zig as c compiler for cross platform builds

sampleBlockCacheConfig.yaml, sampleFileCacheConfigAzure.yaml, sampleFileCacheConfigS3.yaml, sampleFileCacheWithSASConfigAzure.yaml, sampleStreamingConfigAzure.yaml, sampleStreamingConfigS3.yaml, setup/baseConfig.yaml
=> Set network-share true in sample configs

common/types.go, component/libfuse/libfuse2_handler.go
Change the default folder size from 1 PB to 1 TB. This should allow network optix to always allow this drive as a backup drive for storage purposes.
- Closes #
=> Change default cloudfuse size from 1 PB to 1 TB

.github/workflows/code-coverage.yml, cmd/config-gen.go, cmd/config-gen_test.go, cmd/mount.go, cmd/mount_all.go, cmd/secure.go, cmd/secure_set.go, cmd/secure_test.go, common/config/config_parser.go, common/config/config_test.go, common/util.go, common/util_test.go
The passphrase used for securing our config file should be base64 encoded since the cipher key can represent binary data. Before it was assumed the passphrase was the binary data, but this causes issues with non printable characters. Now the passphrase can represent all possible generated cipher keys.
- Closes #
=> Use base64 encoded string for encrypting config file

cmd/health-monitor.go, cmd/mount.go, component/azstorage/azauthmsi.go, component/libfuse/libfuse2_handler.go
All users on a Windows machine are now able to write to mounts by default on Windows. Previously, only the current user could write to the mount. 
- Closes #
=> Use new SDDL option

common/types.go, component/libfuse/libfuse.go, component/libfuse/libfuse2_handler.go, component/libfuse/libfuse_handler_test.go, setup/baseConfig.yaml
=> Add display capacity option

component/file_cache/file_cache_test.go, component/file_cache/lru_policy.go
* `policy.IsCached` needs to be called with a full local path, not an object name.
* `IsCached` was returning false incorrectly because it was being given the wrong path, so fixing that also involved fixing some tests to actually do what was intended.
* Directories do not have their own entries in the cache policy, so calling `IsCached` on a directory will return false even when the directory exists.
* There is a race condition in `TestCloseFile` and `TestRenameDir` that only comes up when a file is deleted right after being closed. The race condition makes `IsCached` return inconsistent results (sometimes it gives a false positive). The race condition is harmless because we only trust negative responses from IsCached. When it returns true, it's basically ignored. I just dropped the …
=> Fix misused IsCached calls in fileCache tests

component/file_cache/file_cache.go, component/file_cache/lru_policy.go, component/libfuse/libfuse2_handler.go, internal/handlemap/handle_map.go
* When calling cacheValidate asynchronously, make sure the file hasn't already been deleted.
* Use LoadAndDelete whenever possible when using a sync map.
- Closes #
=> Fix race conditions

cmd/config-gen_test.go, cmd/secure_test.go, component/file_cache/file_cache_linux_test.go, component/file_cache/file_cache_test.go, component/file_cache/file_cache_windows_test.go, component/file_cache/lru_policy_test.go, component/loopback/loopback_fs_test.go, test/e2e_tests/dir_test.go, test/e2e_tests/file_test.go
Assert has built-in functions to check if a file or directory exists. Use those instead of stat.
This improves assert debugging by providing the reason why the assert failed, as well as being shorter and more readable.
- Closes #
=> Use assert instead of stat in test file and directory existence

component/file_cache/file_cache_linux_test.go, component/file_cache/file_cache_test.go
… since stat will never return that error.
- Closes #
=> Do not check os.IsExist(err) on error returned from stat

component/file_cache/file_cache_linux_test.go, component/file_cache/file_cache_test.go, component/file_cache/file_cache_windows_test.go
Retain test file in file cache by opening a second handle before closing the first
- Closes #
=> Prevent minor race condition in file cache tests

component/file_cache/file_cache_test.go, component/file_cache/file_cache_windows_test.go, component/file_cache/lru_policy.go
In file cache test suite:
* Re-enable tests that were flaky due to race conditions that are fixed now
* Shorten a couple test sleep times
* Remove unnecessary OpenFile when timeout is non-zero
* Remove redundant call to setupTestHelper with config identical to test default config
In lru_policy:
* Remove unused const
* Simplify cacheTimeoutMonitor code
* (calling time.Tick with a zero interval already returns nil, so no need to check if the interval is zero)
* Add comments to updateMarker to explain linked list code
- Closes #
=> Minor improvements in file cache

cmd/generator.go, cmd/mount.go, cmd/mount_all.go, cmd/version.go
Make usage strings use square brackets for optional arguments and angle brackets for required arguments.
Since Cobra already adds "[flags]" to the usage string automatically when a command has flags, change our usage strings to just describe our required arguments and let Cobra do the rest.
Correct usage strings
- Closes #
=> Correct usage strings

.github/workflows/publish-release.yml, .goreleaser.yaml
Lock GoReleaser to v2.3.* to avoid what looks like a name template logic bug in v2.4.
A build with v2.4 failed.
Run a test release?
- [Issues](<link>)
- [Team thread](<link>)
- [Documents](<link>)
- [Email Subject]
=> Specify GoReleaser v2.3 to avoid issue in latest version

.github/workflows/code-coverage.yml, .github/workflows/codeql-analysis.yml, .github/workflows/publish-release.yml, .github/workflows/unit-test.yml, go.mod, go_installer.sh
Latest builds used go 1.23.3 to build cloudfuse, however, there is an issue with daemonizing our application with this version. It does not happen on 1.23.2. Cloudfuse still mounts, but there is an error given that it failed to create a daemon. I'm not sure exactly why, but this is a quick fix.
- Closes #
=> Revert back to go 1.23.2 to avoid daemon issue

component/file_cache/file_cache.go, internal/handlemap/handle_map.go, test/e2e_tests/file_test.go
This fixes a bug where cloudfuse was unable to append to files opened with the O_APPEND flag.
- Closes #369
=> Fix open append

component/file_cache/cache_policy.go, component/file_cache/file_cache.go, component/file_cache/file_cache_test.go, component/file_cache/lru_policy.go, component/file_cache/lru_policy_test.go
This change improves the maintainability of the file cache, to make it easier to add features, and make further changes.
Only do eviction one way: using a timer.
If the timer is zero, use a fast timer (100ms), and evict everything.
Stop using CachePurge for manual evictions. Only use CachePurge when the object is being deleted.
- Closes #
=> Always use timer for eviction

component/file_cache/file_cache.go, component/file_cache/file_cache_test.go, component/file_cache/lru_policy.go, setup/baseConfig.yaml
* Remove zero timeout handling code
* Clean up linked list code
* Update tests
* Update documentation
Make the file cache timeout always at least 1s, and drop zero timeout support code.
- Closes #
=> Make timeout minimum 1s

component/file_cache/file_cache.go, component/file_cache/file_cache_test.go, component/file_cache/lru_policy.go
I used race detector and it identified a number of data races, all in file cache.
This fixes all of those races.
- Closes #
=> Fix race conditions in file cache

component/file_cache/file_cache.go, component/file_cache/file_cache_test.go
* Update open file handles in RenameFile
* Add failure recovery for partial renames to prevent data loss
* Add tests
- Closes #
=> Update open file handles in RenameFile

component/file_cache/cache_policy_test.go, component/file_cache/file_cache.go, component/file_cache/file_cache_linux_test.go, component/file_cache/file_cache_test.go
* A bit of code cleanup.
* Simplify code that clears the lazy flag when a file handle is closed.
* Only close test file handles when it's needed (for Windows). 
* With this change, test cleanup runs correctly, and so tests can reuse filenames without fear of collisions.
* Add assert to make unit tests fail when cleanup fails
In one case handles need to be closed for tests to run correclty, but in most cases it's needed so test cleanup can delete the test files.
Run file cache unit tests on Windows and Linux, and see no errors complaining about failure to cleanup the test.
=> File cache test filenames don't need to be unique anymore!

component/size_tracker/size_tracker.go
This changes the name of the size_tracker file to be based on a combination of the bucket name and the prefix path.
- Closes #
=> Use s3storage name for size_tracking file

component/file_cache/file_cache.go, component/file_cache/file_cache_test.go
Similar to #404, this fixes a bug where renaming the parent directory of an open file clobbers the open file handle.
- Closes #
=> Fix Open File RenameDir Bug

gui/mountPrimaryWindow.py, gui/mountPrimaryWindow.ui
This changes the GUI to only allow mounting as a drive letter on Windows, to reduce user confusion and simplify the Windows mounting process. It replaces the browse button with one for drive letters that display the available drive letters to mount on. The old code is still there, so you can manually type a path and still mount to it, but the browse button in gone.
Here is how the GUI looks now on Windows.
- Closes #
=> Allow GUI to only mount as a drive letter on Windows

build/windows_installer_build_no_gui.iss
Add windows_startup binary to the no_gui installer to allow the user to run cloudfuse service install and have mounts start on remount.
- Closes #
=> Add windows startup to no_gui installer

WINDOWS.md, component/libfuse/libfuse.go, component/libfuse/libfuse2_handler.go, setup/advancedConfig.yaml, setup/baseConfig.yaml
This adds the ability for the user to change the default user / file permissions in windows by passing a SDDL string in the config file. Additionally, adds some instructions and guidance on how to do this.
- Closes #
=> Add support for custom SDDL strings for permissions on Windows

cmd/service_windows.go
Fixes the windows startup link when using the service install command.
- Closes #
=> Fix widows service install command

cmd/root_test.go, cmd/update.go, cmd/update_test.go
This adds a new update command for Cloudfuse. It enables downloading updates from our GitHub releases. It also verifies that the checksum of the download matches the checksum in our release. It currently only supports Linux. Users on Linux should specify either the package type they want to download (deb, rpm) or an output location where the file will be downloaded for the user to install.
- Closes #
=> Add update command for cloudfuse on Linux

cmd/service_windows.go, internal/winservice/registry_windows.go
Use Windows registry for remount on startup instead of the start menu startup folder.
This should ensure Cloudfuse always starts on startup, without requiring a user log in.
- Closes #
=> Change windows service to start using the registry.

cmd/config-gen.go, cmd/mount.go, cmd/secure.go, cmd/secure_test.go, common/encryption.go, common/util.go, common/util_test.go, go.mod
This changes the passphrase field to be an actual password. It uses argon2id to convert that to a key which is then used for the aes encryption of the config file. This should make it easier to use since you can actually just provide a standard password, rather than a base64 encoded aes encryption key.
- Closes #
=> Password is passphrase

.github/workflows/publish-release.yml, README.md
…using apt and dnf repositories
Add rpm and apt repository and automatically upload to it on releases.
- Closes #
=> Add apt and rpm package repositories

cmd/mount_all.go, component/s3storage/client.go, component/s3storage/client_test.go, component/s3storage/connection.go, component/s3storage/s3storage.go, component/s3storage/s3wrappers.go
Having `bucket-name` be optional was broken when `ListBuckets` would return buckets for which the credentials do not provide access. This adds a new function, `filterAccessibleBuckets()`, to call `HeadBucket` on the listed buckets in parallel, and identify the accessible one(s). Then we can choose a default which actually works.
- Closes #
=> Default to first *authorized* bucket

cmd/root.go, cmd/root_test.go
Use a dummy http server running on loopback to prevent running into GitHub's API rate limits in CI
=> Use fake version check in unit tests
